"""initial_schema

Revision ID: 08047910df99
Revises: 
Create Date: 2026-06-22 11:32:08.021491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08047910df99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candles_id'), 'candles', ['id'], unique=False)
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('ldr_setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('range_high', sa.Numeric(), nullable=False),
    sa.Column('range_low', sa.Numeric(), nullable=False),
    sa.Column('range_midpoint', sa.Numeric(), nullable=False),
    sa.Column('swept_side', sa.String(), nullable=False),
    sa.Column('swept_level', sa.Numeric(), nullable=False),
    sa.Column('sweep_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('displacement_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('displacement_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_zone_upper', sa.Numeric(), nullable=True),
    sa.Column('entry_zone_lower', sa.Numeric(), nullable=True),
    sa.Column('invalidation_level', sa.Numeric(), nullable=True),
    sa.Column('target_level', sa.Numeric(), nullable=True),
    sa.Column('estimated_rr', sa.Float(), nullable=True),
    sa.Column('timeframe_context', sa.String(), nullable=False),
    sa.Column('session_label', sa.String(), nullable=True),
    sa.Column('alert_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ldr_setups_id'), 'ldr_setups', ['id'], unique=False)
    op.create_index(op.f('ix_ldr_setups_status'), 'ldr_setups', ['status'], unique=False)
    op.create_index(op.f('ix_ldr_setups_symbol'), 'ldr_setups', ['symbol'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setup_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['setup_id'], ['ldr_setups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_ldr_setups_symbol'), table_name='ldr_setups')
    op.drop_index(op.f('ix_ldr_setups_status'), table_name='ldr_setups')
    op.drop_index(op.f('ix_ldr_setups_id'), table_name='ldr_setups')
    op.drop_table('ldr_setups')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_index(op.f('ix_candles_id'), table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
